### ISSUE TITLE
[BUG] wrong key in lookup_options/Readme

### ISSUE THREAD

**Issue by SimonHoenscheid** [voxpupuli/puppet-hosts#12]
Key in Readme for merge behavior is wrong.

https://github.com/voxpupuli/puppet-hosts/blob/master/README.md?plain=1#L41

Is: 

```yaml
lookup_options:
  hosts::hosts:
    merge:
      strategy: "deep"
```

should be: 

```yaml
lookup_options:
  hosts::entries:
    merge:
      strategy: "deep"
```

I will prepare a fix
